"""Replay labels generated by the foundation model, written, and reused.

The foundation is trained on waters for one epoch. A fine-tune replays other
waters through a head the foundation model relabels, beside a new head read
from its file. What is pinned: the labels are the foundation model's own
numbers and the structures they came from are left alone; a batch that fails
stops everything; the stress weight keeps its two meanings; the artifact reads
back exactly and lives in the run directory; reusing it is refused for another
model or other structures; and the configuration fills in a preset's defaults
without ever overriding a written value.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pytest
import torch
from ase import Atoms
from ase.io import write
from mace_core.config.resolved import ResolvedConfig
from mace_core.data.configuration import Configuration, structures_fingerprint
from mace_core.observables import DEFAULT_CATALOGUE
from mace_torch.cli.run_train import run
from mace_torch.finetune.foundation import read_foundation
from mace_torch.finetune.pseudolabels import (
    PseudolabelError,
    foundation_fingerprint,
    generate_pseudolabels,
    load_pseudolabel_artifact,
    validate_pseudolabel_reuse,
    write_pseudolabel_artifact,
)
from mace_torch.finetune.stages import build, pseudolabel
from mace_torch.train import DataStageError
from test_mace_torch_extend_elements import WATER, water_foundation, waters

SPEC = ResolvedConfig().finetune.pseudolabels


@pytest.fixture(scope="module", name="foundation")
def fixture_foundation(tmp_path_factory):
    return water_foundation(tmp_path_factory.mktemp("water_foundation"))


@pytest.fixture(name="loaded")
def fixture_loaded(foundation, fp64):
    return read_foundation(foundation, DEFAULT_CATALOGUE)


@pytest.fixture(name="fp64")
def fixture_fp64():
    previous = torch.get_default_dtype()
    torch.set_default_dtype(torch.float64)
    try:
        yield
    finally:
        torch.set_default_dtype(previous)


def replay_structures(count=6, seed=11, stress=False):
    generator = np.random.default_rng(seed)
    frames = []
    for _ in range(count):
        atoms = Atoms(
            "OH2",
            positions=WATER + generator.normal(scale=0.05, size=(3, 3)),
            cell=np.eye(3) * 6.0,
            pbc=True,
        )
        atoms.info["REF_energy"] = 99.0
        atoms.arrays["REF_forces"] = np.full((3, 3), 7.0)
        if stress:
            atoms.info["REF_stress"] = np.full(6, 0.5)
        frames.append(atoms)
    return frames


def configurations(count=4, stress_weight=None):
    generator = np.random.default_rng(3)
    items = []
    for index in range(count):
        properties = {
            "energy": 99.0,
            "forces": np.full((3, 3), 7.0),
            "stress": None,
        }
        weights = {"energy": 1.0, "forces": 1.0, "stress": 0.0}
        if stress_weight is not None and index % 2 == 0:
            properties["stress"] = np.full((3, 3), 0.5)
            weights["stress"] = stress_weight
        items.append(
            Configuration(
                atomic_numbers=np.array([8, 1, 1]),
                positions=WATER + generator.normal(scale=0.05, size=(3, 3)),
                properties=properties,
                property_weights=weights,
                cell=np.eye(3) * 6.0,
                pbc=(True, True, True),
                config_type="water",
                head="replay",
            )
        )
    return items


def label(loaded, items, spec=SPEC, batch_size=3, engine=None):
    return generate_pseudolabels(
        engine or loaded.engine,
        items,
        spec,
        z_table=loaded.z_table,
        cutoff=loaded.config.model.r_max,
        head_index=0,
        batch_size=batch_size,
    )


def fine_tune(directory, foundation, **finetune):
    directory.mkdir(parents=True, exist_ok=True)
    write(directory / "replay.xyz", replay_structures())
    write(directory / "new.xyz", waters(8, seed=4))
    pseudolabels = finetune.pop("pseudolabels", {"enabled": True, "heads": ["replay"]})
    return ResolvedConfig.model_validate(
        {
            "runtime": {"work_dir": str(directory), "seed": 5},
            "finetune": {
                "foundation_model": str(foundation),
                "pseudolabels": pseudolabels,
                **finetune,
            },
            "data": {
                "heads": {
                    "replay": {"train_file": str(directory / "replay.xyz")},
                    "new": {
                        "train_file": str(directory / "new.xyz"),
                        "e0s": {"kind": "isolated_atoms"},
                    },
                },
                "valid_fraction": 0.25,
                "pin_memory": False,
            },
            "model": {"observables": ["energy", "forces"]},
            "training": {"max_num_epochs": 1, "batch_size": 4},
        }
    )


# ---------------------------------------------------------------------------
# Generating them
# ---------------------------------------------------------------------------


def test_the_labels_are_the_foundation_model_s_own(loaded):
    items = configurations()
    labelled = label(loaded, items)
    from mace_torch.data import collate_training
    from mace_torch.data.batch import GraphDataset

    dataset = GraphDataset(
        items, cutoff=loaded.config.model.r_max, z_table=loaded.z_table, targets=()
    )
    batch = collate_training(
        [dataset[i] for i in range(len(items))], z_table=loaded.z_table
    )
    direct = loaded.engine(dict(batch.graph), compute=("forces",))
    energies = np.array([item.properties["energy"] for item in labelled])
    forces = np.concatenate([item.properties["forces"] for item in labelled])
    np.testing.assert_allclose(
        energies, direct.total_energy.detach().numpy(), atol=1e-12
    )
    np.testing.assert_allclose(forces, direct.forces.detach().numpy(), atol=1e-12)
    assert all(item.properties["energy"] != 99.0 for item in labelled)


def test_generating_changes_neither_the_structures_nor_the_model(loaded):
    items = configurations()
    before = [dict(item.properties) for item in items]
    flags = [parameter.requires_grad for parameter in loaded.engine.parameters()]
    label(loaded, items)
    assert all(item.properties["energy"] == 99.0 for item in items)
    assert [set(item.properties) for item in items] == [set(p) for p in before]
    assert [
        parameter.requires_grad for parameter in loaded.engine.parameters()
    ] == flags
    assert all(parameter.grad is None for parameter in loaded.engine.parameters())


def saved_bytes(call) -> int:
    """What autograd holds for the backward pass while ``call`` runs."""
    total = [0]

    def pack(tensor):
        total[0] += tensor.numel() * tensor.element_size()
        return tensor

    with torch.autograd.graph.saved_tensors_hooks(pack, lambda tensor: tensor):
        call()
    return total[0]


def test_the_weights_are_constants_while_labelling(loaded):
    """No activation is kept for a weight gradient: the stage holds what the
    model holds with every parameter frozen, and less than with none."""
    items = configurations(1)
    from mace_torch.data import collate_training
    from mace_torch.data.batch import GraphDataset

    dataset = GraphDataset(
        items, cutoff=loaded.config.model.r_max, z_table=loaded.z_table, targets=()
    )
    graph = dict(collate_training([dataset[0]], z_table=loaded.z_table).graph)

    def direct():
        loaded.engine(dict(graph), compute=("forces",), training=False)

    trainable = saved_bytes(direct)
    for parameter in loaded.engine.parameters():
        parameter.requires_grad_(False)
    try:
        frozen = saved_bytes(direct)
    finally:
        for parameter in loaded.engine.parameters():
            parameter.requires_grad_(True)
    labelling = saved_bytes(lambda: label(loaded, items, batch_size=1))
    assert labelling == frozen < trainable
    assert all(parameter.requires_grad for parameter in loaded.engine.parameters())


def test_a_caller_without_gradients_still_gets_forces(loaded):
    """A force is a gradient, so the stage cannot run under ``torch.no_grad()``
    the way the frozen tree's switching off suggests; it turns them on for
    itself and gives the same labels."""
    items = configurations()
    expected = label(loaded, items)
    with torch.no_grad():
        labelled = label(loaded, items)
    for one, two in zip(expected, labelled, strict=True):
        assert np.array_equal(one.properties["forces"], two.properties["forces"])


class _FailsOnSecondCall(torch.nn.Module):
    """The foundation model, until the second batch runs out of memory."""

    def __init__(self, inner):
        super().__init__()
        self.inner = inner
        self.calls = 0

    def forward(self, graph, compute, training):
        self.calls += 1
        if self.calls == 2:
            raise RuntimeError("out of memory")
        return self.inner(graph, compute=compute, training=training)


def test_a_failing_batch_stops_everything(loaded):
    with pytest.raises(PseudolabelError, match="batch 2 of 2"):
        label(loaded, configurations(), engine=_FailsOnSecondCall(loaded.engine))


def test_a_stress_keeps_the_weight_its_file_gave_it(loaded):
    spec = SPEC.model_copy(update={"properties": ("energy", "forces", "stress")})
    labelled = label(loaded, configurations(stress_weight=0.3), spec)
    assert [item.property_weights["stress"] for item in labelled] == [
        0.3,
        0.0,
        0.3,
        0.0,
    ]
    assert labelled[1].properties["stress"] is None

    forced = spec.model_copy(update={"stress_if_missing": True})
    labelled = label(loaded, configurations(stress_weight=0.3), forced)
    assert [item.property_weights["stress"] for item in labelled] == [
        0.3,
        1.0,
        0.3,
        1.0,
    ]
    assert labelled[1].properties["stress"].shape == (3, 3)


def test_a_property_the_model_does_not_produce_is_refused(loaded):
    spec = SPEC.model_copy(update={"properties": ("energy", "dipole")})
    with pytest.raises(PseudolabelError, match="dipole"):
        label(loaded, configurations(), spec)


# ---------------------------------------------------------------------------
# The artifact
# ---------------------------------------------------------------------------


def provenance(loaded, items, **overrides):
    from datetime import UTC, datetime

    from mace_core.config import PseudolabelProvenance

    values = {
        "foundation_model": loaded.name,
        "foundation_fingerprint": foundation_fingerprint(loaded.name),
        "dataset_fingerprint": structures_fingerprint(items),
        "head": "replay",
        "foundation_head": "pbe",
        "spec": SPEC,
        "device": "cpu",
        "dtype": "float64",
        "torch_version": torch.__version__,
        "kernel_backend": "reference",
        "generated_at": datetime(2026, 9, 25, tzinfo=UTC),
        "n_configs": len(items),
        "deterministic": True,
        **overrides,
    }
    return PseudolabelProvenance(**values)


def test_the_artifact_reads_back_exactly(loaded, tmp_path):
    spec = SPEC.model_copy(update={"properties": ("energy", "forces", "stress")})
    labelled = label(loaded, configurations(stress_weight=0.3), spec)
    labelled[1] = Configuration(
        atomic_numbers=labelled[1].atomic_numbers,
        positions=labelled[1].positions,
        properties={**labelled[1].properties, "head": "replay"},
        property_weights=labelled[1].property_weights,
        cell=None,
        pbc=None,
        weight=0.25,
        config_type="odd",
        head="replay",
    )
    record = provenance(loaded, labelled)
    write_pseudolabel_artifact(tmp_path / "replay", labelled, record)
    back, read = load_pseudolabel_artifact(tmp_path / "replay")
    assert read == record
    assert len(back) == len(labelled)
    for written, again in zip(labelled, back, strict=True):
        assert np.array_equal(written.atomic_numbers, again.atomic_numbers)
        assert np.array_equal(written.positions, again.positions)
        assert written.weight == again.weight
        assert written.config_type == again.config_type
        assert written.head == again.head
        assert written.pbc == again.pbc
        assert (written.cell is None) == (again.cell is None)
        assert written.property_weights == again.property_weights
        assert set(written.properties) == set(again.properties)
        for name, value in written.properties.items():
            other = again.properties[name]
            if value is None or isinstance(value, str):
                assert other == value, name
            else:
                assert np.array_equal(np.asarray(value), np.asarray(other)), name
                assert type(value) is type(other) or isinstance(other, np.ndarray)


def test_a_directory_that_is_not_an_artifact_is_refused(tmp_path):
    with pytest.raises(PseudolabelError, match="not a pseudolabel artifact"):
        load_pseudolabel_artifact(tmp_path)


def test_reuse_is_refused_for_another_model_or_other_structures(loaded):
    items = configurations()
    record = provenance(loaded, items)
    right = {
        "foundation_fingerprint": record.foundation_fingerprint,
        "dataset_fingerprint": record.dataset_fingerprint,
    }
    validate_pseudolabel_reuse(record, **right)
    with pytest.raises(PseudolabelError, match="weights"):
        validate_pseudolabel_reuse(
            record, **{**right, "foundation_fingerprint": "0" * 64}
        )
    moved = configurations()
    moved[0].positions = moved[0].positions + 1e-9
    with pytest.raises(PseudolabelError, match="other structures"):
        validate_pseudolabel_reuse(
            record, **{**right, "dataset_fingerprint": structures_fingerprint(moved)}
        )


def test_version_drift_warns_only_for_labels_that_cannot_be_made_again(loaded):
    items = configurations()
    later = {"torch_version": "9.9.9", "kernel_backend": "reference"}
    for deterministic, expected in ((True, 0), (False, 1)):
        record = provenance(loaded, items, deterministic=deterministic)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            validate_pseudolabel_reuse(
                record,
                foundation_fingerprint=record.foundation_fingerprint,
                dataset_fingerprint=record.dataset_fingerprint,
                **later,
            )
        assert len(caught) == expected


# ---------------------------------------------------------------------------
# In a run
# ---------------------------------------------------------------------------


def test_a_run_writes_its_labels_into_its_own_directory(
    foundation, loaded, tmp_path, monkeypatch
):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path / "cache"))
    config = fine_tune(tmp_path / "run", foundation)
    built = build(config)
    artifact = tmp_path / "run" / "pseudolabels" / "replay"
    labelled, record = load_pseudolabel_artifact(artifact)
    assert record.foundation_head == "pbe"
    assert record.n_configs == len(labelled) == 6
    assert record.deterministic
    assert all(item.properties["energy"] != 99.0 for item in labelled)
    assert not (tmp_path / "cache").exists()
    assert sorted(path.name for path in tmp_path.iterdir()) == ["run"]
    assert dict(built.data.e0s.values["replay"]) == dict(loaded.e0s["pbe"])


def test_a_later_run_reuses_them_by_naming_them(foundation, tmp_path):
    first = fine_tune(tmp_path / "first", foundation)
    build(first)
    labels = tmp_path / "first" / "pseudolabels"
    reused = fine_tune(
        tmp_path / "second",
        foundation,
        pseudolabels={"labels_from": str(labels), "heads": ["replay"]},
    )
    trained = run(reused)
    assert trained.checkpoint_path is not None
    assert not (tmp_path / "second" / "pseudolabels").exists()


def test_labels_for_other_structures_are_refused(foundation, tmp_path):
    first = fine_tune(tmp_path / "first", foundation)
    build(first)
    other = fine_tune(
        tmp_path / "second",
        foundation,
        pseudolabels={
            "labels_from": str(tmp_path / "first" / "pseudolabels"),
            "heads": ["replay"],
        },
    )
    write(tmp_path / "second" / "replay.xyz", replay_structures(seed=12))
    with pytest.raises(PseudolabelError, match="other structures"):
        build(other)


def test_the_standalone_step_writes_what_a_run_writes(foundation, tmp_path):
    config = fine_tune(tmp_path / "run", foundation)
    written = pseudolabel(config, "replay", tmp_path / "sweep")
    alone, alone_record = load_pseudolabel_artifact(written / "replay")
    build(config)
    in_run, run_record = load_pseudolabel_artifact(
        tmp_path / "run" / "pseudolabels" / "replay"
    )
    assert alone_record.dataset_fingerprint == run_record.dataset_fingerprint
    assert json.loads((written / "replay" / "manifest.json").read_text()) == json.loads(
        (tmp_path / "run" / "pseudolabels" / "replay" / "manifest.json").read_text()
    )
    for one, two in zip(alone, in_run, strict=True):
        assert one.properties["energy"] == two.properties["energy"]
    reused = fine_tune(
        tmp_path / "second",
        foundation,
        pseudolabels={"labels_from": str(written), "heads": ["replay"]},
    )
    assert run(reused).checkpoint_path is not None


def test_a_relabelled_head_with_no_structures_is_refused(foundation, tmp_path):
    config = fine_tune(tmp_path / "run", foundation)
    write(tmp_path / "run" / "replay.xyz", [])
    with pytest.raises(DataStageError, match="replay"):
        build(config)


# ---------------------------------------------------------------------------
# The configuration
# ---------------------------------------------------------------------------


def resolved(**sections):
    return ResolvedConfig.model_validate(
        {
            "finetune": {"foundation_model": "fm.json", **sections.pop("finetune", {})},
            "data": {
                "heads": {
                    "replay": {"curated": "mp"},
                    "new": {"train_file": "new.xyz"},
                }
            },
            **sections,
        }
    )


def test_the_multihead_preset_fills_in_what_is_not_written():
    config = resolved(finetune={"preset": "multihead"})
    assert config.training.lr == 1e-4
    assert config.training.ema.enabled and config.training.ema.decay == 0.99999
    assert config.finetune.pseudolabels.enabled
    assert config.finetune.pseudolabels.properties == ("energy", "forces")
    assert config.pseudolabelled_heads == ("replay",)
    assert config.finetune.preset_values == {
        "training.lr": "multihead",
        "training.ema": "multihead",
        "finetune.pseudolabels.enabled": "multihead",
    }
    assert ResolvedConfig.model_validate(config.model_dump(mode="json")) == config


def test_a_written_value_always_wins_over_the_preset():
    config = resolved(
        finetune={"preset": "multihead", "pseudolabels": {"enabled": False}},
        training={"lr": 0.005, "ema": {"enabled": False}},
    )
    assert config.training.lr == 0.005
    assert not config.training.ema.enabled
    assert not config.finetune.pseudolabels.enabled
    assert config.finetune.preset_values == {}


def test_there_is_no_flag_that_forces_a_preset():
    from mace_core.config.pseudolabels import PseudolabelConfig
    from mace_core.config.resolved import FinetuneConfig
    from mace_core.config.training import TrainingConfig

    fields = [
        name
        for section in (FinetuneConfig, PseudolabelConfig, TrainingConfig)
        for name in section.model_fields
    ]
    assert not [name for name in fields if "force" in name]


def test_a_relabelled_head_takes_the_foundation_s_energies():
    config = resolved(finetune={"pseudolabels": {"enabled": True}})
    assert config.data.heads["replay"].e0s.kind == "foundation"
    assert config.data.heads["new"].e0s.kind == "isolated_atoms"
    with pytest.raises(ValueError, match="kind 'foundation'"):
        ResolvedConfig.model_validate(
            {
                "finetune": {
                    "foundation_model": "fm.json",
                    "pseudolabels": {"enabled": True},
                },
                "data": {
                    "heads": {"replay": {"curated": "mp", "e0s": {"kind": "average"}}}
                },
            }
        )


def test_generating_and_reusing_at_once_is_refused():
    with pytest.raises(ValueError, match="Set one"):
        resolved(finetune={"pseudolabels": {"enabled": True, "labels_from": "x"}})


def test_labels_need_a_foundation_model_and_a_head():
    with pytest.raises(ValueError, match="foundation_model"):
        ResolvedConfig.model_validate(
            {
                "finetune": {"pseudolabels": {"enabled": True}},
                "data": {"heads": {"replay": {"curated": "mp"}}},
            }
        )
    with pytest.raises(ValueError, match="no head is relabelled"):
        ResolvedConfig.model_validate(
            {
                "finetune": {
                    "foundation_model": "fm.json",
                    "pseudolabels": {"enabled": True},
                },
                "data": {"heads": {"new": {"train_file": "new.xyz"}}},
            }
        )


def test_the_legacy_flags_land_on_the_section():
    from argparse import Namespace

    from mace_core.config.legacy import from_namespace

    values = from_namespace(
        Namespace(pseudolabel_replay=True, pseudolabel_replay_compute_stress=True)
    )
    assert values["finetune"]["pseudolabels"] == {
        "enabled": True,
        "stress_if_missing": True,
    }


def test_a_head_s_weight_does_not_reach_its_written_labels(foundation, tmp_path):
    config = fine_tune(tmp_path / "run", foundation)
    heads = dict(config.data.heads)
    heads["replay"] = heads["replay"].model_copy(update={"weight": 0.5})
    config = config.model_copy(
        update={"data": config.data.model_copy(update={"heads": heads})}
    )
    built = build(config)
    labelled, _ = load_pseudolabel_artifact(
        tmp_path / "run" / "pseudolabels" / "replay"
    )
    assert {item.weight for item in labelled} == {1.0}
    assert built is not None


def test_the_labels_live_nowhere_but_the_run(foundation, tmp_path):
    config = fine_tune(tmp_path / "run", foundation)
    build(config)
    written = sorted(
        str(path.relative_to(tmp_path))
        for path in Path(tmp_path).rglob("*.safetensors")
    )
    assert "run/pseudolabels/replay/labels.safetensors" in written
